import React from 'react';

import './../css/Header.css';

import github from './../images/github.png';

var timeout;

class Header extends React.Component {
  state = {
    term: ""
  }

  /**
   * Calls component function to send search term to parent.
   * Uses timeout to simulate the app waiting for user to finish typing.
   * 
   * @param {Object} e Event generated by the onChange prop of search term input
   */
  updateTerm(e) {
    this.setState({term: e.target.value});
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      if(this.state.term !== "")
      {
        this.props.onSearch(this.state.term);
      }
    }, 1000);
  }

  /**
   * Handler for when user hits enter to clear timout and submit search term
   * 
   * @param {Object} e Event generated by the onKeyPress prop of search term input
   */
  handleKeyPress(e) {
    if(e.key === "Enter")
    {  
      clearTimeout(timeout);
      this.props.onSearch(this.state.term);
    }
  }

  render() {
    return (
      <div className="header">
        <img className="brand" src={github} alt="GitHub"/>
        <input
          className="headerInput"
          value={this.state.term}
          onChange={(e) => this.updateTerm(e)}
          placeholder="Search by username or email"
          onKeyPress={(e) => this.handleKeyPress(e)}
        />
        <button className="searchButton" onClick={() => this.props.onSearch(this.state.term)}>Search</button>
        {(this.props.results || this.props.results === 0) &&
          <p className="headerResults">{this.props.results} results</p>
        }
      </div>
    )
  }
}

export default Header;
